export const HCM_LIST = [
  'VŨ CÔNG NGHĨA',
  'NGUYỄN THỊ NGỌC BÍCH',
  'QUÁCH TẤN ĐẠT',
  'TRẦN THỊ THUÝ HÀ',
  'LÂM VĂN PHƯƠNG',
  'NGUYỄN THỊ CẨM NGÂN',
  'ĐẶNG THỊ NGỌC HỒNG',
  'NGÔ VĂN TE',
  'TRẦN THỊ KHÁNH VÂN',
  'THÁI CHÂU MINH DUY',
  'HUỲNH QUỐC TOÀN',
  'NGUYỄN THỊ HỒNG HẠNH',
  'ĐỖ HÔNG DIỆU',
  'LÊ NGỌC TÍM',
  'TRẦN THỊ BÍCH NGỌC',
  'BÀNH THU PHƯỢNG',
  'NGUYỄN THỊ NHƯ QUỲNH',
  'VÕ MINH TRƯỜNG',
  'TRẦN PHƯỚC MINH ĐĂNG',
  'HỒ VIỆT TIẾN',
  'PHAN VĂN TUẤN',
  'ĐÀO TRỌNG NHÂN',
  'NGUYỄN THỊ PHƯƠNG DUNG',
  'Phạm Bá Cường',
  'NGUYỄN NGỌC ĐÀI TRANG',
  'TRẦN THỊ MỸ YẾN',
  'NGUYỄN VĂN TÂM',
  'LÊ HOÀNG TƯỜNG LÂM',
  'NGUYỄN THỊ LINH',
  'CHÂU THỊ DIỄM THANH',
  'NGUYỄN MINH SANG',
  'PHẠM NHƯ QUANG',
  'HỀ NGỌC BÍCH',
  'NGÔ KHẮC KIÊN',
  'LÊ QUỐC TRƯỞNG',
  'NGUYỄN THỊ MỸ YẾN',
  'TRẦN VĂN HIỀN',
  'TẠ ĐỨC LUÂN',
  'NGUYỄN XUÂN TIẾN',
  'TRẦN THỊ MINH KHA',
  'NGUYỄN SƠN PHI',
  'TRẦN TRỌNG THỨC',
  'NGUYỄN THỊ TUYẾT NHUNG',
  'HÀ THỊ BẠCH TUYẾT',
  'VÕ LÊ VÂN',
  'ĐỖ THỊ NGỌC THUỶ',
  'NGUYỄN ĐÌNH LÀNH',
  'PHẠM THỊ MAI HẬU',
  'TÔ HỒNG NHIÊN',
  'ĐÀO THỊ HƯƠNG THUỶ',
  'NGUYỄN ĐỖ HẢI NGỌC',
  'LAI MINH TRANG',
  'NGUYỄN THỊ NGỌC YẾN',
  'BÙI THỊ NGỌC TÚ',
  'NGUYỄN THỊ KIM TUYẾN',
  'LÊ ĐĂNG KHOA',
  'CAO THẾ SƠN',
  'NGUYỄN HOÀNG TRẬN',
  'A ẢNH',
  'HÀ KIM ANH',
  'LÝ HỒNG DÂN',
  'NGUYỄN VIẾT THỊNH',
  'LÊ ĐÌNH QUỲNH',
  'LÊ HỒNG PHƯƠNG',
  'TRẦN NGỌC HIẾN',
  'TRẦN THỊ THANH THÀ',
  'ĐỖ DUY HỒNG',
  'THẠCH MINH HIỀN',
  'NGUYỄN THỊ MINH HIỀN',
  'DANH PHƯỚC QUÝ',
  'NÔNG HỮU HOAN',
  'BÙI MAI NGUYỆT ÁNH',
  'NAY THỊ THUÝ',
  'LƯƠNG THỊ RẠNG',
  'VÕ THỊ KIM NGÂN',
  'NGUYỄN LÊ NHẬT QUANG',
  'TRẦN NHƯ TRỌNG ÂN',
  'HỮU THỊ TRÚC MAI',
  'NGUYỄN THỊ ÚT',
  'TRẦN BÙI HOÀI VỌNG',
  'LÂM MINH LỘC',
  'NGUYỄN HỮU MẠNH ĐỨC',
  'VÕ QUANG HÂN',
  'NGUYỄN THỊ CẨM NHUNG',
  'LÊ HOÀNG KIM',
  'NGUYỄN THẾ HÙNG',
  'NGUYỄN HUỲNH NHẬT QUANG',
  'TRẦN HỒNG ÂN',
  'HUỲNH QUỐC CƯỜNG',
  'ĐOÀN VĂN TIẾP',
  'NGUYỄN THÀNH TÂM',
  'ĐÀO CAO NHÂN',
  'PHẠM VĂN LỘC',
  'TĂNG XUÂN BÁCH',
  'HUỲNH VĂN TÍNH',
  'Phan Thị Vương Châu',
  'TRỊNH HỒNG VÂN',
  'NGUYỄN VĂN TRÃI',
  'TÔ THANH ỬNG',
  'LÂM TRẦN TUẤN',
  'Phạm Thanh Huyền Trang',
  'NGUYỄN ĐOÀN THÀNH TÂM',
  'HUỲNH THỊ THANH TUYỀN',
  'NGUYỄN MINH TRƯỜNG',
  'VÕ THỊ THANH THẢO',
  'ĐOÀN NAM TRƯỞNG',
  'NGÔ TÚ LOAN',
  'LÊ MINH PHƯỢNG',
  'TRẦN THỊ NGỌC SƯƠNG',
  'NGUỸEN THUÝ HẰNG',
  'NGUYỄN QUỐC VIỆT',
  'TÔ VĂN TUẤN',
  'ĐỖ HỮU TRƯỜNG HẢI',
  'KHƯU THỊ LAN PHƯƠNG',
  'LƯU NGỌC TRÂN',
  'SƠN THỊ NGỌC GIÀU',
  'CAO QUỐC HOÀI',
  'PHẠM TÙNG SƠN',
  'TRẦN HỒ MỸ TIÊN',
  'THÁI PHƯƠNG QUANG',
  'NGÔ VĂN THUYỀN',
  'PHAN THANH HỒNG',
  'HỒ THỊ NHƯ Ý',
  'PHẠM THỊ SUM',
  'NGUYỄN NGUYÊN HẠNH',
  'TRẦN THỊ NGỌC XUÂN',
  'LÊ MINH CHÂU',
  'HỒ ĐỨC HÒA',
  'TRẦN THỊ TUYẾT NHUNG',
];

export const HN_LIST = [
  'VŨ THỊ NGHINH',
  'PHẠM THỊ MAI PHƯƠNG',
  'TRẦN DUY CƯỜNG',
  'PHẠM TUẤN THẮNG',
  'TRẦN HỒNG NHÃ',
  'LÊ THU QUYÊN',
  'ĐẶNG THỊ TRANG',
  'NGUYỄN THỊ NGỌC LAN',
  'BÙI THỊ MỸ UYÊN',
  'NGUYỄN THỊ CẨM THUÝ',
  'ĐÀO ĐỨC PHONG',
  'Nhung Kiều Hồng',
  'PHÙNG QUỐC TOẢN',
  'Nguyễn Thị Như Quỳnh',
  'Nguyen Quynh Xuan',
  'Lưu Tuấn Thành',
  'NGUYỄN QUANG MINH',
  'Nguyen Thi Ly',
  'TỐNG MINH CÔNG',
  'LƯƠNG VĂN NAM',
  'ĐINH ĐỨC HÒA',
  'NGUYỄN DANH QUÝ',
  'ĐOÀN THỊ TUYẾT',
  'NGUYỄN NGỌC LÂN',
  'TRẦN THỊ MINH HẰNG',
  'NGUYỄN VĂN DOANH',
  'PHẠM THỊ THU HÀ',
  'NGUYỄN VĂN QUÝNH',
  'NGÔ CHÍ HIẾU',
  'NGUYỄN VĂN MÙI',
  'Nguyễn thanh Sơn',
  'liên đoàn thị Hồng',
  'LÊ THỊ THANH HẰNG',
  'NGUYỄN THỊ NGỌC THẮNG',
  'TRỊNH NGỌC ANH',
  'NGUYỄN MINH TÂM',
  'DƯƠNG THU ANH',
  'ĐỖ XUÂN CHIẾN',
  'NGÔ ĐỨC MẠNH',
  'NGUYỄN QUỲNH HOA',
  'ĐỖ VIẾT THẮNG',
  'NGUYỄN XUÂN THÀNH',
  'PHẠM THU HÀ',
  'NGUYỄN VĂN QUYẾT',
  'HOÀNG HẢI HÀ',
  'PHẠM THỊ MAI',
  'TRẦN THỊ HOA HUYỀN',
  'TRƯƠNG THỊ LY',
  'Lê Thị Hương Trầm',
  'Nguyễn Ngọc Cầu',
  'Trần Xuân Hưng',
  'Nguyễn Văn Quân',
  'Nguyễn Khôi Nguyên',
  'Lô Thị Ánh',
  'Đặng Xuân Trung',
  'Võ Đình Hạnh',
  'Nguyễn Thị Thùy DƯơng',
  'Mã Thị Thúy Hằng',
  'ĐINH DANH TRÌNH',
  'ĐỖ MẠNH HÙNG',
  'ĐỖ DOÃN TRỌNG',
  'NGUYỄN THANH MAI',
  'HOÀNG QUỐC VIỆT',
  'NGUYỄN THỊ DUNG',
  'TRẦN KHANH',
  'NGUYỄN THỊ HUYỀN',
  'TRẦN QUANG ĐỊNH',
  'NGUYỄN ANH DŨNG',
  'BÙI THỊ DIỆU LINH',
  'NGUYỄN THỊ MAI',
  'LÊ THỊ HẠNH',
  'DƯƠNG THỊ THIẾT',
  'NGUYỄN THỊ THANH',
  'LÊ THỊ THU HÀ',
  'NGUYỄN TRUNG DŨNG',
  'ĐÀO ANH TÚ',
  'PHẠM NGỌC DŨNG',
  'NGUYỄN THỊ HỒNG DUYÊN',
  'PHẠM THỊ THANH LOAN',
  'NGUYỄN VIẾT GIỎI',
  'HOÀNG THỊ DIỄM HƯƠNG',
  'ĐẶNG THỊ KIM THANH',
  'NGUYỄN THÚY QUỲNH',
  'ĐÀM HƯƠNG LIÊN',
  'NGUYỄN THỊ NGỌC DIỆP',
  'NGUYỄN THỊ HIỀN',
  'PHẠM THỊ XINH',
  'NGUYỄN VĂN TĂNG',
  'NGUYỄN ĐỨC DU',
  'NGUYỄN THỊ THU MINH',
  'NGUYỄN THỊ HÀ',
  'QUẢN THỊ LIÊN HƯƠNG',
  'PHẠM THỊ TRANG LINH',
  'HOÀNG THU HẰNG',
  'NGUYÊN THỊ LỆ THU',
  'ĐÀO BÍCH HƯỜNG',
  'NGUYỄN VĂN QUANG',
  'HOÀNG MINH HƯƠNG',
  'TRẦN THỊ THANH THUỶ',
  'NGUYỄN VĂN SƠN',
  'LÊ THANH NAM',
  'TRẦN ĐÌNH TIẾN',
  'NGUYỄN TRÀ GIANG',
  'PHẠM ANH DŨNG',
  'LÊ THUÝ NGỌC',
  'HOÀNG ĐÌNH CƯỜNG',
  'NGUYỄN CÔNG HÀ',
  'TRẦN THU HÀ',
  'TRẦN VĂN HIẾU',
  'PHÙNG THỊ LÝ',
  'PHẠM ANH HÙNG',
  'LÊ THỊ THẢO',
  'VŨ THỊ TRANG',
  'NGUYỄN MAI HƯƠNG',
  'NGUYỄN THẾ NAM HUY',
  'NGUYỄN THỊ QUỲNH TRANG',
  'CHU THỊ HẰNG',
  'HOÀNG MINH LỢI',
  'LÊ CAO KHÁNH',
  'LÊ QUANG THIỆN',
  'NGUYỄN VĂN DẦN',
  'TRẦN VĂN ĐÔNG',
  'TRẦN NGỌC DŨNG',
  'NGUYỄN ĐĂNG DƯƠNG',
  'CHU QUỐC HOÀNG',
  'TRẦN THỊ LAN ANH',
  'BÙI MINH THU',
  'ĐỖ CÔNG HUÂN',
  'ĐỖ ĐÌNH QUANG',
  'ĐỖ GIA NAM',
  'ĐỖ ĐÌNH ĐIỂU',
  'HOÀNG BẢO TRUNG',
  'HOÀNG MỸ LỆ DUNG',
  'MAI HUYỀN TRANG',
  'NGUYỄN HỒNG HẠNH',
  'NGUYỄN NGỌC MAI',
  'NGUYỄN THỊ LỆ MỸ',
  'NGUYỄN THỊ PHƯƠNG THÚY',
  'NGUYỄN THỊ TÂM',
  'THÁI THỊ HẠNH',
  'TRẦN LỆ THỦY',
  'TRẦN THỊ NHƯ QUỲNH',
  'VŨ MINH PHÚC',
  'Lê Văn Hưng',
  'Trần Thị Hậu',
  'Nguyễn Văn Hiếu',
  'Nguyễn Thị Hồng',
  'Nguyễn Tiến Huy',
  'Cao Thị Phương Thuý',
  'Nguyễn Văn Phương',
  'Phạm Thị Xuân',
  'Nguyễn Quang Phúc',
  'Trần Thị Hải Yến',
  'Trần Quốc Việt',
  'Trần Việt Cường',
  'Nguyễn Quốc Việt',
  'LÊ THỊ HIỀN',
  'NGUYỄN QUANG VINH',
  'NGUYỄN THỊ THANH XUÂN',
  'TRẦN THỊ GIANG',
  'TRẦN VĂN LƯU',
  'ĐOÀN THỊ LEN',
  'HOÀNG ĐỨC HUY',
  'KHUẤT DUY ANH',
  'LẠI XUÂN VĨNH',
  'PHẠM THANH TÙNG',
  'NGUYỄN THỊ KIM ANH',
  'NGUYỄN THỊ THU LY',
  'NGUYỄN TRUNG ĐỨC',
  'PHẠM NHƯ QUỲNH',
  'PHẠM VĂN HƯNG',
  'PHAN DIỄM QUỲNH',
  'TRẦN MAI NGUYÊN',
  'NGUYỄN DIỆP THƠ',
  'NGUYỄN VĂN TOÀN',
  'BÙI THỊ NGUYỆT ÁNH',
  'NGUYỂN ĐĂNG KHOA',
  'NGUYỄN HỮU LƯƠNG',
  'ĐINH HOÀNG MINH',
  'HOÀNG KHÁNH LINH',
  'BÙI THÚY HỒNG',
  'TRẦN THỊ THÚY',
  'VŨ QUỲNH TRANG',
  'TÔ THỊ VÂN GIANG',
  'TRẦN VĂN LAI',
  'NGUYỄN MẠNH TÂN',
  'BÙI THỊ THANH HÀ',
  'ĐINH HẢI NAM',
  'LÊ THẾ KIÊN',
  'NGUYỄN TRUNG HIẾU',
  'NGUYỄN VĂN THỰC',
  'VŨ QUỲNH NGA',
  'NGUYỄN XUÂN TÚ',
  'TRẦN THỊ AN',
  'PHẠM THỊ AN',
  'PHẠM VĂN TÙNG',
  'TRẦN THANH HOA',
  'LÊ QUANG HUY',
  'VŨ ĐÌNH HƯNG',
  'NGUYỄN ĐÌNH TUẤN',
  'LẠI THỊ BẠCH YẾN',
  'TRẦN THỊ LINH TÚ',
  'LÊ THỊ HOÀI THU',
  'NGUYỄN ĐÌNH THÁI',
  'HOÀNG THỊ MINH TÂM',
  'ĐỖ QUANG TÙNG',
  'PHẠM THỊ OANH',
  'NGUYỄN ĐÌNH PHÚC',
  'TRẦN XUÂN TÌNH',
  'NGUYỄN MẠNH CHIẾN',
  'NGUYỄN THỊ PHƯỢNG',
  'NGUYỄN HỒNG NHUNG',
  'PHẠM NGỌC THANH',
  'LÊ THỊ BÍCH HẠNH',
  'NGUYỄN THỊ BẰNG TÂM',
  'PHẠM THỊ THÚY HẰNG',
  'NGUYỄN THỊ NGỌC ANH',
];
