export const HCM_LIST = [
  'NGUYỄN ĐỖ HẢI NGỌC',
  'NGUYỄN THỊ NGỌC BÍCH',
  'NGUYỄN HUỲNH NHẬT QUANG',
  'VÕ LÊ VÂN',
  'BÀNH THU PHƯỢNG',
  'TRẦN THỊ BÍCH NGỌC',
  'TRẦN THỊ KHÁNH VÂN',
  'LÊ ĐÌNH QUỲNH',
  'CAO THẾ SƠN',
  'NGUYỄN THỊ TUYẾT NHUNG',
  'TRẦN NHƯ TRỌNG ÂN',
  'NGUYỄN THẾ HÙNG',
  'VŨ CÔNG NGHĨA',
  'ĐÀO THỊ HƯƠNG THUỶ',
  'NGUYỄN HỮU MẠNH ĐỨC',
  'VÕ QUANG HÂN',
  'TRẦN NGỌC HIẾN',
  'TẠ ĐỨC LUÂN',
  'TRẦN VĂN HIỀN',
  'LÊ QUỐC TRƯỞNG',
  'NAY THỊ THUÝ',
  'NÔNG HỮU HOAN',
  'HỒ VIỆT TIẾN',
  'NGUYỄN XUÂN TIẾN',
  'VÕ THỊ KIM NGÂN',
  'TRẦN THỊ MINH KHA',
  'NGUYỄN VĂN TÂM',
  'LÊ HOÀNG TƯỜNG LÂM',
  'NGUYỄN THỊ NGỌC YẾN',
  'ĐẶNG THỊ NGỌC HỒNG',
  'NGUYỄN THỊ HỒNG HẠNH',
  'NGUYỄN THỊ MỸ YẾN',
  'PHẠM TÙNG SƠN',
  'NGUYỄN THỊ NHƯ QUỲNH',
  'NGUYỄN MINH SANG',
  'NGUYỄN THỊ PHƯƠNG DUNG',
  'PHẠM NHƯ QUANG',
  'NGUYỄN THỊ KIM TUYẾN',
  'ĐÀO TRỌNG NHÂN',
  'ĐỖ THỊ NGỌC THUỶ',
  'TRẦN PHƯỚC MINH ĐĂNG',
  'TRẦN BÙI HOÀI VỌNG',
  'CAO QUỐC HOÀI',
  'NGUYỄN ĐÌNH LÀNH',
  'Phạm Thanh Huyền Trang',
  'Phạm Bá Cường',
  'Phan Thị Vương Châu',
  'ĐỖ HỮU TRƯỜNG HẢI',
  'A ẢNH',
  'NGÔ KHẮC KIÊN',
  'ĐÀO CAO NHÂN',
  'HỒ THỊ NHƯ Ý',
  'HÀ KIM ANH',
  'NGUYỄN THỊ CẨM NGÂN',
  'NGUYỄN THỊ MINH HIỀN',
  'THÁI CHÂU MINH DUY',
  'THÁI PHƯƠNG QUANG',
  'NGÔ VĂN THUYỀN',
  'VÕ MINH TRƯỜNG',
  'TRỊNH HỒNG VÂN',
  'LÊ HỒNG PHƯƠNG',
  'LÊ ĐĂNG KHOA',
  'THẠCH MINH HIỀN',
  'LAI MINH TRANG',
  'KHƯU THỊ LAN PHƯƠNG',
  'HỮU THỊ TRÚC MAI',
  'BÙI THỊ NGỌC TÚ',
  'NGUYỄN MINH TRƯỜNG',
  'NGUYỄN HOÀNG TRẬN',
  'NGUYỄN THỊ ÚT',
  'ĐỖ DUY HỒNG',
  'LÊ NGỌC BÍCH',
  'ĐỖ HÔNG DIỆU',
  'TÔ HỒNG NHIÊN',
  'TRẦN HỒ MỸ TIÊN',
  'NGUỸEN THUÝ HẰNG',
  'LÝ HỒNG DÂN',
  'PHẠM THỊ MAI HẬU',
  'NGUYỄN ĐOÀN THÀNH TÂM',
  'LÊ HOÀNG KIM',
  'TRẦN HỒNG ÂN',
  'NGUYỄN THÀNH TÂM',
  'SƠN THỊ NGỌC GIÀU',
  'QUÁCH TẤN ĐẠT',
  'LÂM MINH LỘC',
  'HUỲNH QUỐC CƯỜNG',
  'NGUYỄN VIẾT THỊNH',
  'NGUYỄN NGỌC ĐÀI TRANG',
  'TRẦN THỊ THANH THÀ',
  'TRẦN THỊ TUYẾT NHUNG',
  'TĂNG XUÂN BÁCH',
  'TÔ THANH ỬNG',
  'HUỲNH QUỐC TOÀN',
  'NGUYỄN THỊ CẨM NHUNG',
  'LƯU NGỌC TRÂN',
  'NGUYỄN LÊ NHẬT QUANG',
  'NGÔ VĂN TE',
  'ĐOÀN NAM TRƯỞNG',
  'HUỲNH VĂN TÍNH',
  'DANH PHƯỚC QUÝ',
  'HÀ THỊ BẠCH TUYẾT',
  'LÊ NGỌC TÍM',
  'PHAN THANH HỒNG',
  'HUỲNH THỊ THANH TUYỀN',
  'CHÂU THỊ DIỄM THANH',
  'LÂM VĂN PHƯƠNG',
  'ĐOÀN VĂN TIẾP',
  'NGUYỄN QUỐC VIỆT',
  'NGUYỄN THỊ LINH',
  'NGUYỄN VĂN TRÃI',
  'PHẠM THỊ SUM',
  'LƯƠNG THỊ RẠNG',
  'PHAN VĂN TUẤN',
  'TRẦN THỊ NGỌC SƯƠNG',
  'TRẦN THỊ NGỌC XUÂN',
  'LÊ MINH PHƯỢNG',
  'NGÔ TÚ LOAN',
  'TRẦN THỊ THUÝ HÀ',
  'TRẦN TRỌNG THỨC',
  'NGUYỄN NGUYÊN HẠNH',
  'TÔ VĂN TUẤN',
  'LÂM TRẦN TUẤN',
  'VÕ THỊ THANH THẢO',
  'BÙI MAI NGUYỆT ÁNH',
  'PHẠM VĂN LỘC',
  'LÊ MINH CHÂU',
  'HỒ ĐỨC HÒA',
  'NGUYỄN SƠN PHI',
];

export const HN_LIST = [
  'VŨ THỊ NGHINH',
  'PHẠM THỊ MAI PHƯƠNG',
  'TRẦN DUY CƯỜNG',
  'PHẠM TUẤN THẮNG',
  'TRẦN HỒNG NHÃ',
  'LÊ THU QUYÊN',
  'ĐẶNG THỊ TRANG',
  'NGUYỄN THỊ NGỌC LAN',
  'BÙI THỊ MỸ UYÊN',
  'NGUYỄN THỊ CẨM THUÝ',
  'ĐÀO ĐỨC PHONG',
  'Nhung Kiều Hồng',
  'PHÙNG QUỐC TOẢN',
  'Nguyễn Thị Như Quỳnh',
  'Nguyen Quynh Xuan',
  'Lưu Tuấn Thành',
  'NGUYỄN QUANG MINH',
  'Nguyen Thi Ly',
  'TỐNG MINH CÔNG',
  'LƯƠNG VĂN NAM',
  'ĐINH ĐỨC HÒA',
  'NGUYỄN DANH QUÝ',
  'ĐOÀN THỊ TUYẾT',
  'NGUYỄN NGỌC LÂN',
  'TRẦN THỊ MINH HẰNG',
  'NGUYỄN VĂN DOANH',
  'PHẠM THỊ THU HÀ',
  'NGUYỄN VĂN QUÝNH',
  'NGÔ CHÍ HIẾU',
  'NGUYỄN VĂN MÙI',
  'Nguyễn thanh Sơn',
  'liên đoàn thị Hồng',
  'LÊ THỊ THANH HẰNG',
  'NGUYỄN THỊ NGỌC THẮNG',
  'TRỊNH NGỌC ANH',
  'NGUYỄN MINH TÂM',
  'DƯƠNG THU ANH',
  'ĐỖ XUÂN CHIẾN',
  'NGÔ ĐỨC MẠNH',
  'NGUYỄN QUỲNH HOA',
  'ĐỖ VIẾT THẮNG',
  'NGUYỄN XUÂN THÀNH',
  'PHẠM THU HÀ',
  'NGUYỄN VĂN QUYẾT',
  'HOÀNG HẢI HÀ',
  'PHẠM THỊ MAI',
  'TRẦN THỊ HOA HUYỀN',
  'TRƯƠNG THỊ LY',
  'Lê Thị Hương Trầm',
  'Nguyễn Ngọc Cầu',
  'Trần Xuân Hưng',
  'Nguyễn Văn Quân',
  'Nguyễn Khôi Nguyên',
  'Lô Thị Ánh',
  'Đặng Xuân Trung',
  'Võ Đình Hạnh',
  'Nguyễn Thị Thùy DƯơng',
  'Mã Thị Thúy Hằng',
  'ĐINH DANH TRÌNH',
  'ĐỖ MẠNH HÙNG',
  'ĐỖ DOÃN TRỌNG',
  'NGUYỄN THANH MAI',
  'HOÀNG QUỐC VIỆT',
  'NGUYỄN THỊ DUNG',
  'TRẦN KHANH',
  'NGUYỄN THỊ HUYỀN',
  'TRẦN QUANG ĐỊNH',
  'NGUYỄN ANH DŨNG',
  'BÙI THỊ DIỆU LINH',
  'NGUYỄN THỊ MAI',
  'LÊ THỊ HẠNH',
  'DƯƠNG THỊ THIẾT',
  'NGUYỄN THỊ THANH',
  'LÊ THỊ THU HÀ',
  'NGUYỄN TRUNG DŨNG',
  'ĐÀO ANH TÚ',
  'PHẠM NGỌC DŨNG',
  'NGUYỄN THỊ HỒNG DUYÊN',
  'PHẠM THỊ THANH LOAN',
  'NGUYỄN VIẾT GIỎI',
  'HOÀNG THỊ DIỄM HƯƠNG',
  'ĐẶNG THỊ KIM THANH',
  'NGUYỄN THÚY QUỲNH',
  'ĐÀM HƯƠNG LIÊN',
  'NGUYỄN THỊ NGỌC DIỆP',
  'NGUYỄN THỊ HIỀN',
  'PHẠM THỊ XINH',
  'NGUYỄN VĂN TĂNG',
  'NGUYỄN ĐỨC DU',
  'NGUYỄN THỊ THU MINH',
  'NGUYỄN THỊ HÀ',
  'QUẢN THỊ LIÊN HƯƠNG',
  'PHẠM THỊ TRANG LINH',
  'HOÀNG THU HẰNG',
  'NGUYÊN THỊ LỆ THU',
  'ĐÀO BÍCH HƯỜNG',
  'NGUYỄN VĂN QUANG',
  'HOÀNG MINH HƯƠNG',
  'TRẦN THỊ THANH THUỶ',
  'NGUYỄN VĂN SƠN',
  'LÊ THANH NAM',
  'TRẦN ĐÌNH TIẾN',
  'NGUYỄN TRÀ GIANG',
  'PHẠM ANH DŨNG',
  'LÊ THUÝ NGỌC',
  'HOÀNG ĐÌNH CƯỜNG',
  'NGUYỄN CÔNG HÀ',
  'TRẦN THU HÀ',
  'TRẦN VĂN HIẾU',
  'PHÙNG THỊ LÝ',
  'PHẠM ANH HÙNG',
  'LÊ THỊ THẢO',
  'VŨ THỊ TRANG',
  'NGUYỄN MAI HƯƠNG',
  'NGUYỄN THẾ NAM HUY',
  'NGUYỄN THỊ QUỲNH TRANG',
  'CHU THỊ HẰNG',
  'HOÀNG MINH LỢI',
  'LÊ CAO KHÁNH',
  'LÊ QUANG THIỆN',
  'NGUYỄN VĂN DẦN',
  'TRẦN VĂN ĐÔNG',
  'TRẦN NGỌC DŨNG',
  'NGUYỄN ĐĂNG DƯƠNG',
  'CHU QUỐC HOÀNG',
  'TRẦN THỊ LAN ANH',
  'BÙI MINH THU',
  'ĐỖ CÔNG HUÂN',
  'ĐỖ ĐÌNH QUANG',
  'ĐỖ GIA NAM',
  'ĐỖ ĐÌNH ĐIỂU',
  'HOÀNG BẢO TRUNG',
  'HOÀNG MỸ LỆ DUNG',
  'MAI HUYỀN TRANG',
  'NGUYỄN HỒNG HẠNH',
  'NGUYỄN NGỌC MAI',
  'NGUYỄN THỊ LỆ MỸ',
  'NGUYỄN THỊ PHƯƠNG THÚY',
  'NGUYỄN THỊ TÂM',
  'THÁI THỊ HẠNH',
  'TRẦN LỆ THỦY',
  'TRẦN THỊ NHƯ QUỲNH',
  'VŨ MINH PHÚC',
  'Lê Văn Hưng',
  'Trần Thị Hậu',
  'Nguyễn Văn Hiếu',
  'Nguyễn Thị Hồng',
  'Nguyễn Tiến Huy',
  'Cao Thị Phương Thuý',
  'Nguyễn Văn Phương',
  'Phạm Thị Xuân',
  'Nguyễn Quang Phúc',
  'Trần Thị Hải Yến',
  'Trần Quốc Việt',
  'Trần Việt Cường',
  'Nguyễn Quốc Việt',
  'LÊ THỊ HIỀN',
  'NGUYỄN QUANG VINH',
  'NGUYỄN THỊ THANH XUÂN',
  'TRẦN THỊ GIANG',
  'TRẦN VĂN LƯU',
  'ĐOÀN THỊ LEN',
  'HOÀNG ĐỨC HUY',
  'KHUẤT DUY ANH',
  'LẠI XUÂN VĨNH',
  'PHẠM THANH TÙNG',
  'NGUYỄN THỊ KIM ANH',
  'NGUYỄN THỊ THU LY',
  'NGUYỄN TRUNG ĐỨC',
  'PHẠM NHƯ QUỲNH',
  'PHẠM VĂN HƯNG',
  'PHAN DIỄM QUỲNH',
  'TRẦN MAI NGUYÊN',
  'NGUYỄN DIỆP THƠ',
  'NGUYỄN VĂN TOÀN',
  'BÙI THỊ NGUYỆT ÁNH',
  'NGUYỂN ĐĂNG KHOA',
  'NGUYỄN HỮU LƯƠNG',
  'ĐINH HOÀNG MINH',
  'HOÀNG KHÁNH LINH',
  'BÙI THÚY HỒNG',
  'TRẦN THỊ THÚY',
  'VŨ QUỲNH TRANG',
  'TÔ THỊ VÂN GIANG',
  'TRẦN VĂN LAI',
  'NGUYỄN MẠNH TÂN',
  'BÙI THỊ THANH HÀ',
  'ĐINH HẢI NAM',
  'LÊ THẾ KIÊN',
  'NGUYỄN TRUNG HIẾU',
  'NGUYỄN VĂN THỰC',
  'VŨ QUỲNH NGA',
  'NGUYỄN XUÂN TÚ',
  'TRẦN THỊ AN',
  'PHẠM THỊ AN',
  'PHẠM VĂN TÙNG',
  'TRẦN THANH HOA',
  'LÊ QUANG HUY',
  'VŨ ĐÌNH HƯNG',
  'NGUYỄN ĐÌNH TUẤN',
  'LẠI THỊ BẠCH YẾN',
  'TRẦN THỊ LINH TÚ',
  'LÊ THỊ HOÀI THU',
  'NGUYỄN ĐÌNH THÁI',
  'HOÀNG THỊ MINH TÂM',
  'ĐỖ QUANG TÙNG',
  'PHẠM THỊ OANH',
  'NGUYỄN ĐÌNH PHÚC',
  'TRẦN XUÂN TÌNH',
  'NGUYỄN MẠNH CHIẾN',
  'NGUYỄN THỊ PHƯỢNG',
  'NGUYỄN HỒNG NHUNG',
  'PHẠM NGỌC THANH',
  'LÊ THỊ BÍCH HẠNH',
  'NGUYỄN THỊ BẰNG TÂM',
  'PHẠM THỊ THÚY HẰNG',
  'NGUYỄN THỊ NGỌC ANH',
];
